apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-example
  template:
    metadata:
      labels:
        app: kubernetes-example
    spec:
      containers:
        - name: kubernetes-example
          image: 123456giri/kubernetes-example:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
